name: circular_theme_reveal
description: A beautiful Telegram-style circular reveal animation for theme transitions in Flutter.
version: 1.0.0
homepage: https://github.com/YOUR_USERNAME/circular_theme_reveal

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

