name: circular_theme_reveal
description: A beautiful Telegram-style circular reveal animation for theme transitions in Flutter. Smooth, performant, and zero dependencies.
version: 1.0.2
homepage: https://github.com/MarcosPereira1/flutter_telegram_theme
repository: https://github.com/MarcosPereira1/flutter_telegram_theme
issue_tracker: https://github.com/MarcosPereira1/flutter_telegram_theme/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

topics:
  - animation
  - theme
  - telegram
  - circular-reveal
  - dark-mode

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

